Step1 is completed
AccountingApp-Group2/AccountingApp pull request #22
Opened 2022-05-29 14:42 UTC by AbbosB12

2022-05-29 21:08 UTC, VitalySlabada commented
Looks good but could not test, someone or Abbos please test

2022-05-29 21:09 UTC, VitalySlabada approved these changes

2022-05-29 22:24 UTC, josephum commented
Please remove category_id from payment.
Keep it as below. It works:
INSERT INTO payment (created_by, created_time, is_deleted, updated_by, updated_time, amount, institution_id, is_paid, month, year, company_id)
VALUES (1, '2022-01-05 00:00:00', FALSE, 1, '2022-01-05 00:00:00', 100.00, '1', true, 'January','01/15/2022',2),
       (2, '2022-01-05 00:00:00', FALSE, 1, '2022-01-05 00:00:00', 95.09, '2', false, 'May', '05/12/2022',1),
       (3, '2022-01-05 00:00:00', FALSE, 1, '2022-01-05 00:00:00', 45.87, '3', true, 'June', '06/1/2022',3);

2022-05-29 23:16 UTC, josephum requested changes

2022-05-29 23:16 UTC, josephum commented on src/main/resources/data.sql
> +INSERT INTO payment (created_by, created_time, is_deleted, updated_by, updated_time, amount, institution_id, is_paid, month, year, company_id,category_id)
I think category_id does not apply to payment

2022-05-30 03:44 UTC, josephum approved these changes

2022-05-30 03:45 UTC, merged