Step2 abbos company
AccountingApp-Group2/AccountingApp pull request #39
Opened 2022-06-06 00:22 UTC by AbbosB12

Please review

2022-06-06 02:34 UTC, BahaMaksudov reviewed
Added a comment regarding Edit Company functionality. Please check and confirm.

2022-06-06 02:34 UTC, BahaMaksudov commented on src/main/java/com/example/accountingapp/controller/CompanyController.java
> +    }
Edit functionality if not updating State. This is part of CRUD and maybe not worked on yet. Please confirm. Thank you.

2022-06-06 10:32 UTC, MehmetKaldirim approved these changes
list work properly  good job, just next time please merge master before create a pull request ...

2022-06-07 00:40 UTC, AccountingApp-Group2 requested changes, later dismissed
phone does not show up, please fix before merging

![image](https://user-images.githubusercontent.com/106039489/172271730-777d3918-e7a6-43f3-89fd-305aafe82525.png)


<img width="294" alt="image" src="https://user-images.githubusercontent.com/106039489/172271858-255e4cf0-a4f3-4f1c-a34c-6094fafb3699.png">

2022-06-07 00:42 UTC, VitalySlabada commented
I left the comment about the phone :) was signed in in different account - I think it just needs some data in sql to be added

2022-06-08 08:11 UTC, MehmetKaldirim approved these changes
There are three  bugs for edit , establishment date,status  and states dont change after update, u re taking data from db and save it same into db , if u have time please try to fix them...

2022-06-08 14:29 UTC, VitalySlabada commented
@MehmetKaldirim 
I think Abbos is still on step 2
No need to do crud, only list properly

2022-06-19 05:25 UTC, josephum commented
IdeaProjects/AccountingApp/src/main/java/com/example/accountingapp/controller/CompanyController.java:45:23
java: cannot find symbol
  symbol:   method save(com.example.accountingapp.dto.CompanyDTO)
  location: variable companyService of type com.example.accountingapp.service.CompanyService

Some CRUD methods like save are not implemented

2022-06-23 13:14 UTC, AbbosB12 commented
Crud Operation work properly

2022-06-23 20:09 UTC, MehmetKaldirim approved these changes

2022-06-25 17:10 UTC, josephum approved these changes

2022-06-25 17:16 UTC, merged