Logged in as
AccountingApp-Group2/AccountingApp pull request #72
Opened 2022-07-17 23:52 UTC by Bear4TW

-Changed the 'Logged in as' section to first and last name
-added 2 methods to UserPrincipal

2022-07-18 03:16 UTC, josephum requested changes
You need to include the first name and last name in the logout menu, top right corner

2022-07-18 05:23 UTC, Bear4TW commented
Changed 'account' to 'first last'
Removed 'Settings'

2022-07-19 15:13 UTC, josephum approved these changes

2022-07-19 22:30 UTC, AbbosB12 approved these changes

2022-07-19 22:37 UTC, merged